name: Dagelijkse scraper & deploy

on:
  schedule:
    - cron: '0 4 * * *'  # Elke dag om 04:00 UTC (06:00 NL tijd)
  workflow_dispatch:      # Hiermee kun je de workflow ook handmatig starten

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonen
        uses: actions/checkout@v3

      - name: Installeer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installeer vereiste Python packages
        run: pip install openai requests beautifulsoup4

      - name: Voer AI-scraper uit
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scraper_ai.py

      - name: Installeer Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # Vervang dit eventueel met jouw exacte versie

      - name: Flutter Web build uitvoeren
        run: flutter build web

      - name: Deploy naar Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KORTINGFINDER }}"
          channelId: live
          projectId: kortingfinder
          entryPoint: ./
