name: Dagelijkse scraper & deploy

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonen
        uses: actions/checkout@v3

      - name: Installeer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installeer OpenAI package
        run: pip install openai

      - name: Voer AI-scraper uit
        run: python scraper_ai.py

      - name: Deploy naar Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KORTINGFINDER }}"
          channelId: live
          projectId: kortingfinder
          entryPoint: ./
